dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('home-page', home_page, name='home_page'),
    path('home-page-public', home_page_public, name='home_page_public'),
]

new_campaign_urlpatterns = [
    path('crowdfunding/public/<str:campaign_id>/preview', cf_public_preview, name='cf_public_preview'),
    path('new-campaign/<str:campaign_id>/<str:create_or_update>', new_campaign, name='new_campaign'),
    path('create-new-campaign', create_new_campaign, name='create_new_campaign'),
    path('publish-new-campaign/<str:campaign_id>', publish_new_campaign, name='publish_new_campaign'),
    path('pick-plan', pick_plan, name='pick_plan'),

    # ajax
    path('new-campaign-process/<str:process>', new_campaign_process, name='new_campaign_process'),
    path('new-campaign-process-delete', new_campaign_process_delete, name='new_campaign_process_delete'),
    path('small-medias-upload', small_medias_upload, name='small_medias_upload'),
]

urlpatterns += new_campaign_urlpatterns

cf_urlpatterns = [
    path('crowdfunding/public/<str:campaign_id>', cf_public, name='cf_public'),
    path('crowdfunding/manager', cf_manager, name='cf_manager'),
]

urlpatterns += cf_urlpatterns

giving_pilot/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def test(request):
    return render(request, 'icons/temp.html')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
] + [path('test', test, name='test')]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.urls import path

app_name = 'landing'

urlpatterns = [

]

dashboard/views/crowdfunding.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404

from dashboard.models import Media
from dashboard.permissions import is_campaign_owner
from dashboard.utils import *


def cf_public(request, campaign_id):
    campaign = get_object_or_404(Campaign, id=campaign_id)
    small_medias = Media.objects.filter(campaign=campaign).order_by('-created_at')
    context = {
        'campaign': campaign,
        'small_medias': small_medias,
        'campaigns': Utils.get_all_published_campaigns(),
        'is_public': True,
    }

    return render(request, 'dashboard/crowdfunding/public/cf_public.html', context)


@is_campaign_owner
def cf_manager(request):
    return render(request, 'dashboard/crowdfunding/manager/cf_manager.html')


@login_required
@is_campaign_owner
def cf_public_preview(request, campaign_id):
    campaign = get_object_or_404(Campaign, id=campaign_id)
    small_medias = Media.objects.filter(campaign=campaign).order_by('-created_at')
    context = {
        'campaign': campaign,
        'campaigns': Utils.get_all_published_campaigns(),
        'small_medias': small_medias,
        'is_preview': True,
    }
    return render(request, 'dashboard/crowdfunding/public/cf_public_preview.html', context)

dashboard/views/new_campaign.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt

from accounts.models import User
from dashboard.models import Media, Category
from dashboard.permissions import is_campaign_owner
from dashboard.utils import *


@login_required
def create_new_campaign(request):
    user = User.objects.get(username=request.user.username)
    campaign = Campaign(owner=user)
    campaign.save()
    return redirect(f'/dashboard/new-campaign/{campaign.id}/create')


@login_required
@is_campaign_owner
def publish_new_campaign(request, campaign_id):
    campaign = get_object_or_404(Campaign, id=campaign_id)
    campaign.is_published = True
    campaign.save()
    return redirect('dashboard:home_page')


@login_required
def new_campaign(request, campaign_id, create_or_update):
    campaign = get_object_or_404(Campaign, id=campaign_id)
    small_medias = Media.objects.filter(campaign=campaign).order_by('-created_at')
    context = {
        'campaign_id': campaign_id,
        'campaign': campaign,
        'is_update_url': True if create_or_update == 'update' else False,
        'categories': Category.objects.all(),
        'small_medias': small_medias,
        'tags': campaign.tags.split(', ') if campaign.tags else [],
        'causes': campaign.cause.split(', ') if campaign.cause else [],
        'on_creating': True
    }
    if campaign.organization_name or campaign.title or campaign.category:
        context['is_update'] = True
    if 'tab' in request.GET:
        context['tab'] = request.GET.get('tab').strip()
    if 'tag' in request.GET:
        context['tag'] = request.GET.get('tag').strip()
    return render(request, 'dashboard/new_campaign/campaign_base.html', context)


@login_required
@csrf_exempt
def new_campaign_process(request, process):
    if request.method == 'POST':
        uuid = request.POST.get('uuid')
        campaign = Campaign.objects.get(id=uuid)
        if process == 'basic_info':
            org_name = request.POST.get('org_name')
            org_description = request.POST.get('org_description')
            if request.FILES:
                org_logo = request.FILES.popitem()[1][0]
                campaign.organization_logo = org_logo
            campaign.organization_name = org_name
            campaign.organization_description = org_description
        if process == 'about_campaign':
            camp_title = request.POST.get('camp_title')
            camp_description = request.POST.get('camp_description')
            # camp_cause = request.POST.get('camp_cause')
            camp_start_date = request.POST.get('camp_start_date')
            has_camp_end_date = request.POST.get('has_camp_end_date')
            camp_end_date = request.POST.get('camp_end_date')
            has_goal_amount = request.POST.get('has_goal_amount')
            camp_goal_amount = request.POST.get('camp_goal_amount')
            campaign.title = camp_title
            campaign.description = camp_description
            # campaign.cause = camp_cause
            is_update = True if request.POST['is_update'] == 'true' else False
            thumbnail_path = ''
            print(123123123, is_update)
            if is_update:
                if campaign.large_media:
                    try:
                        os.remove(os.path.join(settings.MEDIA_ROOT, campaign.large_media.name))
                    except:
                        pass
                if campaign.large_image:
                    try:
                        os.remove(os.path.join(settings.MEDIA_ROOT, campaign.large_image.replace('media/', '')))
                    except:
                        pass
                if campaign.large_media_thumbnail:
                    t_url = campaign.large_media_thumbnail.replace(Utils.get_protocol_and_host(request), '').replace(
                        'media/', '')
                    try:
                        os.remove(os.path.join(settings.MEDIA_ROOT, t_url))
                    except:
                        pass
                campaign.large_media = ''
                campaign.large_image = ''
                campaign.large_media_url = ''
                campaign.large_is_video = False
            if request.FILES:
                campaign.large_media = request.FILES.popitem()[1][0]
                campaign.save()
                thumbnail_path = os.path.join(Utils.get_protocol_and_host(request), 'media', 'thumbnail',
                                              Utils.get_thumbnail(campaign.large_media.name, media_type='video'))
                campaign.large_is_video = True

            elif 'canvas' in request.POST:
                campaign.large_image = base64_to_image(bs64_data=request.POST['canvas'],
                                                       username=request.POST['username'])
                thumbnail_path = os.path.join(Utils.get_protocol_and_host(request), 'media', 'thumbnail',
                                              Utils.get_thumbnail(campaign.large_image, media_type='image'))
            elif 'url' in request.POST:
                campaign.large_media_url = request.POST.get('url')
                thumbnail_path = os.path.join(Utils.get_protocol_and_host(request), 'media', 'thumbnail',
                                              Utils.get_thumbnail(campaign.large_media_url, media_type='url'))
                campaign.large_is_video = True
            if thumbnail_path != '':
                campaign.large_media_thumbnail = thumbnail_path + '_thumbnail.jpg'
                campaign.large_media_cover = thumbnail_path + '_cover.jpg'
                campaign.large_media_cover_small = thumbnail_path + '_cover_small.jpg'
            campaign.start_date = camp_start_date
            campaign.has_end_date = True if has_camp_end_date == 'true' else False
            if has_camp_end_date == 'false':
                campaign.end_date = datetime.date.today() + datetime.timedelta(days=720)
            else:
                campaign.end_date = camp_end_date
            campaign.has_goal_amount = True if has_goal_amount == 'true' else False
            campaign.goal_amount = camp_goal_amount
        if process == 'about_you':
            your_name = request.POST.get('your_name')
            your_email = request.POST.get('your_email')
            your_phone = request.POST.get('your_phone')
            your_title = request.POST.get('your_title')
            is_your_email_private = True if request.POST.get('is_your_email_private') == 'true' else False
            is_your_phone_private = True if request.POST.get('is_your_phone_private') == 'true' else False
            is_your_title_private = True if request.POST.get('is_your_title_private') == 'true' else False
            campaign.full_name = your_name
            campaign.second_email = your_email
            campaign.mobile = your_phone
            campaign.your_title = your_title
            campaign.is_your_title_private = is_your_title_private
            campaign.is_mobile_private = is_your_phone_private
            campaign.is_email_private = is_your_email_private
        if process == 'other_options':
            category_id = request.POST.get('category')
            tags = request.POST.get('tags')
            is_camp_searchable = True if request.POST.get('is_camp_searchable') == 'true' else False
            is_camp_private = True if request.POST.get('is_camp_private') == 'true' else False
            category = Category.objects.get(id=category_id)
            campaign.category = category
            campaign.is_campaign_searchable = is_camp_searchable
            campaign.tags = tags
            campaign.is_campaign_private = is_camp_private
        campaign.save()

        return JsonResponse({
            'result': 'success'
        }, status=201)


@csrf_exempt
def new_campaign_process_delete(request):
    if request.method == 'POST':
        uuid = request.POST.get('uuid')
        # Campaign.objects.filter(id=uuid).delete()
        return JsonResponse({
            'result': 'success'
        }, status=202)


@csrf_exempt
def small_medias_upload(request):
    if request.method == 'POST':
        uuid = request.POST.get('uuid')
        campaign = get_object_or_404(Campaign, id=uuid)
        keep_media_ids = [value for key, value in request.POST.items() if 'media_id_' in key]
        is_created_indices = [key.replace('is_created_', '') for key in request.POST if 'is_created_' in key]
        medias = Media.objects.filter(campaign=campaign).exclude(id__in=keep_media_ids)
        for media in medias:
            if media.file:
                os.remove(os.path.join(settings.MEDIA_ROOT, media.file.name))
            if media.image:
                os.remove(os.path.join(settings.MEDIA_ROOT, media.image.replace('media/', '')))
            if media.thumbnail:
                t_url = media.thumbnail.replace(Utils.get_protocol_and_host(request), '').replace('media/', '')
                os.remove(os.path.join(settings.MEDIA_ROOT, t_url))
        medias.delete()
        for index in is_created_indices:
            if 'canvas_' + index in request.POST:
                image = base64_to_image(request.POST['canvas_' + index], request.POST['username'])
                thumbnail_path = os.path.join(Utils.get_protocol_and_host(request), 'media', 'thumbnail',
                                              Utils.get_thumbnail(image, media_type='image', is_small=True))
                Media(campaign=campaign, image=image, thumbnail=thumbnail_path).save()

            elif 'url_' + index in request.POST:
                media_url = request.POST['url_' + index]
                thumbnail_path = os.path.join(Utils.get_protocol_and_host(request), 'media', 'thumbnail',
                                              Utils.get_thumbnail(media_url, media_type='url', is_small=True))

dashboard/templates/dashboard/new_campaign/process/about_you.html
{% load static %}
<div id="nc-about-you" class="about-you campaign-content tab-body d-none" data-navlink="item-you">
    <div class="title mt-4">About You</div>
    <div class="text-cus-secondary">Tell us about yourself and add members to help manage your campaign</div>
    <div class="content form-group">
        <div class="item name">
            <label for="name" class="w-100">
                <div class="d-flex justify-content-between">
                    <div class="text-cus-dark d-flex align-items-center "><b>Your Name</b></div>
                </div>
            </label>
            <div class="alert alert-danger d-none your-name-required">Your name is required.</div>
            <input type="text" class="your-name form-control" placeholder="Adam Voigt" value="{{ campaign.full_name }}">
        </div>
        <div class="item email">
            <label for="email" class="w-100">
                <div class="d-flex justify-content-between">
                    <div class="text-cus-dark d-flex align-items-center "><b>Email Address</b></div>
                    <div class="d-flex align-items-center">
                        <div class="toggle-keep-private-email custom-control custom-switch">
                            <input type="checkbox"
                                   class="custom-control-input {% if campaign.is_email_private %}checked{% endif %}"
                                   id="toggle-keep-private-email" {% if campaign.is_email_private %}checked{% endif %}>
                            <label class="custom-control-label text-cus-dark" for="toggle-keep-private-email">
                                Keep Private
                            </label>
                        </div>
                    </div>
                </div>
            </label>
            <div class="alert alert-danger d-none your-email-required">Your email is required.</div>
            <input type="text" class="your-email form-control" placeholder="example@email.com"
                   value="{{ campaign.second_email }}">
        </div>
        <div class="item phone">
            <label for="phone" class="w-100">
                <div class="d-flex justify-content-between">
                    <div class="text-cus-dark d-flex align-items-center "><b>Phone</b></div>
                    <div class="d-flex align-items-center">
                        <div class="toggle-keep-private-phone custom-control custom-switch">
                            <input type="checkbox"
                                   class="custom-control-input {% if campaign.is_mobile_private %}checked{% endif %}"
                                   id="toggle-keep-private-phone"
                                   {% if campaign.is_mobile_private %}checked{% endif %}>
                            <label class="custom-control-label text-cus-dark" for="toggle-keep-private-phone">
                                Keep Private
                            </label>
                        </div>
                    </div>
                </div>
            </label>
            <div class="alert alert-danger d-none your-phone-required">Your phone number is required.</div>
            <input type="text" class="your-phone form-control" placeholder="+1 123456789" value="{{ campaign.mobile }}">
        </div>
        <div class="item">
            <label for="title" class="w-100">
                <div class="d-flex justify-content-between">
                    <div class="text-cus-dark d-flex align-items-center "><b>Title</b></div>
                    <div class="d-flex align-items-center">
                        <div class="toggle-keep-private-title custom-control custom-switch">
                            <input type="checkbox"
                                   class="custom-control-input {% if campaign.is_your_title_private %}checked{% endif %}"
                                   id="toggle-keep-private-title"
                                   {% if campaign.is_your_title_private %}checked{% endif %}>
                            <label class="custom-control-label text-cus-dark" for="toggle-keep-private-title">
                                Keep Private
                            </label>
                        </div>
                    </div>
                </div>
            </label>
            <div class="alert alert-danger d-none your-title-required">Your email is required.</div>
            <input type="text" class="your-title form-control" placeholder="Ex. Product manager"
                   value="{{ campaign.your_title }}">
        </div>
        {#        <div class="item show-contact-btn">#}
        {#            <div class="toggle-show-contact custom-control custom-switch">#}
        {#                <input type="checkbox" class="custom-control-input" id="toggle-show-contact"#}
        {#                       checked>#}
        {#                <label class="custom-control-label text-cus-dark" for="toggle-show-contact">#}
        {#                    Keep Private#}
        {#                </label>#}
        {#            </div>#}
        {#            <div class="mt-2" style="padding-left: 37px">#}
        {#                <div class="with-info"><p class="text-cus-secondary">#}
        {#                    If you enable this, users will be able to send message directly to the campaign manager's#}
        {#                    email.</p>#}
        {#                </div>#}
        {#            </div>#}
        {#        </div>#}
        <div class="bottom mt-5">
            <div class="back btn-cus btn-cus-primary mr-3" onclick="onAboutYouBack()">Back</div>
            <div class="next btn-cus btn-cus-secondary" onclick="onAboutYouNext()">Next</div>
        </div>
    </div>
    <div class="hidden-field">
        <input type="text" class="save-url" value="{% url 'dashboard:new_campaign_process' 'about_you' %}" hidden>
    </div>
</div>

dashboard/templates/dashboard/new_campaign/process/basic_info.html
{% load static %}
<div id="nc-basic-info" class="basic-info d-none campaign-content tab-body" data-navlink="item-basic">
    <div class="sub-title mt-4">
        Basic Information
    </div>
    <div class="text-cus-secondary">
        Tell us about your campaign organization
    </div>
    <div class="info">
        <!--
        <div class="type row m-0 mt-4">
            <div class="title col-lg-3 p-0">Type</div>
            <div class="btn-cus btn-cus-group col-lg-9 p-0">
                <div class="item active">Crowdfunding</div>
                <div class="item">Peer-to-Peer</div>
            </div>
        </div>
        -->
        <div class="form-group">
            <div class="mt-5">
                <div class="alert alert-danger org-name-required d-none">
                    Organization name is required.
                </div>
                <input type="text" id="org-name" class="form-control" name="organization" value="{{ campaign.organization_name }}"
                       placeholder="Name of Organization">
            </div>
            <div class="mt-4">
                <div class="alert alert-danger org-description-required d-none">
                    Organization description is required.
                </div>
                <textarea id="org-description" class="" placeholder="Description of your organization ...">{{ campaign.organization_description }}</textarea>
            </div>
        </div>
        <div class="upload-logo mt-4">
            <input type="file" hidden>
            <div class="logo-img">
                <img id="logo-img-src" class="img" src="{{ campaign.organization_logo.url }}" alt="company-logo">
            </div>
            <div class="logo-action">
                <div class="sub-title">
                    Add your organization's logo
                </div>
                <input type="file" id="input-logo" hidden>
                <div class="btn-cus btn-cus-primary mt-auto" onclick="onClickUploadLogo()">Upload</div>
            </div>
        </div>
        <div class="bottom pt-5">
            <div class="back btn-cus btn-cus-primary mr-3" onclick="onBasicInfoBack()">Back</div>
            <div class="next btn-cus btn-cus-secondary" onclick="onBasicInfoNext()">Next</div>
        </div>
    </div>
    <div class="hidden-field">
        <input type="text" class="save-url" value="{% url 'dashboard:new_campaign_process' 'basic_info' %}" hidden>
    </div>
</div>

dashboard/templates/dashboard/new_campaign/process/other_options.html
{% load static %}
<div id="nc-other-options" class="other-options d-none campaign-content tab-body" data-navlink="item-other">
    <div class="title mt-4">Other Options</div>
    <div class="text-cus-secondary">Tell us about yourself and add members to help your campaign</div>
    <div class="content mb-5">
        <div class="item category">
            <div class="form-group with-icon">
                <select class="camp-category form-control border-0" style="background-color: #f2f3f5!important;">
                    {% for category in categories %}
                        <option value="{{ category.id }}"
                                {% if campaign.category == category %}selected{% endif %}>{{ category.name }}</option>
                    {% endfor %}
                </select>
                <div class="icon"><i class="fas fa-chevron-down text-cus-primary"></i></div>
            </div>
        </div>
        <div class="item searchable">
            <div class="switch-with-line">
                <div class="toggle-searchable custom-control custom-switch mt-4">
                    <input type="checkbox"
                           class="custom-control-input {% if campaign.is_campaign_searchable %}checked{% endif %}"
                           id="toggle-searchable" {% if campaign.is_campaign_searchable %}checked{% endif %}>
                    <label class="custom-control-label text-cus-dark" for="toggle-searchable">
                        <b>Make my Campaign Searchable</b></label>
                </div>
                <div class="line" style="height: 150px"></div>
            </div>
            <div style="padding-left: 37px">
                <div class="with-info mt-2"><p class="text-cus-secondary">
                    Users will be able to search your campaign inside Giving Pilot Website</p>
                </div>
                <div class="text-cus-dark"><b>Add tags and keywords to improve your campaign's discoverability</b>
                </div>
                <div class="add-tags mt-2">
                    {% for tag in tags %}
                        <div class="tag {% if forloop.last %}end-tag{% endif %} tag-{{ forloop.counter0 }}">{{ tag }}<span
                                onclick="onDeleteTag('tag-{{ forloop.counter0 }}')">&times;</span>
                        </div>
                    {% endfor %}
                    <div class="form-group m-0 p-0">
                        <input type="text" class="form-control new-tag" style="outline: none">
                    </div>
                </div>
                <div class="text-cus-secondary mt-2"><i>Press enter to separate</i></div>
            </div>
        </div>
        <div class="item private">
            <div class="toggle-private custom-control custom-switch mt-4">
                <input type="checkbox"
                       class="custom-control-input {% if campaign.is_campaign_private %}checked{% endif %}"
                       id="toggle-private" {% if campaign.is_campaign_private %}checked{% endif %}>
                <label class="custom-control-label text-cus-dark" for="toggle-private">
                    <b>Make my Campaign Private</b></label>
            </div>
            <div style="padding-left: 37px">
                <div class="with-info mt-2"><p class="text-cus-secondary">
                    If you enable this option users without invitation will not be able to see details of your
                    campaign.</p>
                </div>
            </div>
        </div>
        {#        <div class="item custom-url">#}
        {#            <div class="toggle-custom-url custom-control custom-switch mt-4">#}
        {#                <input type="checkbox" class="custom-control-input" id="toggle-custom-url" checked>#}
        {#                <label class="custom-control-label text-cus-dark" for="toggle-custom-url">#}
        {#                    <b>Custom URL</b></label>#}
        {#            </div>#}
        {#            <div style="padding-left: 37px">#}
        {#                <div class="d-flex flex-row form-group">#}
        {#                    <div class="text-cus-dark d-flex justify-content-center align-items-center mr-3">#}
        {#                        <b>www.givingpilot.com/</b>#}
        {#                    </div>#}
        {#                    <input type="text" class="form-control" placeholder="type here ...">#}
        {#                </div>#}
        {#            </div>#}
        {#        </div>#}
    </div>
    <div class="alert alert-danger checking-process d-none">You should complete the following process. <br><span
            class="detail-process"></span></div>
    <div class="bottom">
        <div class="back btn-cus btn-cus-primary mr-3" onclick="onOtherOptionsBack()">Back</div>
        <div class="next btn-cus btn-cus-secondary" onclick="onOtherOptionsNext()">Preview</div>
    </div>
    <div class="hidden-field">
        <input type="text" class="save-url" value="{% url 'dashboard:new_campaign_process' 'other_options' %}" hidden>
        <input type="text" class="preview-url" value="{% url 'dashboard:cf_public_preview' campaign_id %}" hidden>
    </div>
</div>

dashboard/templates/dashboard/new_campaign/process/terms_and_conditions.html
{% load static %}
<div id="nc-terms-and-conditions" class="tab-body terms-and-conditions campaign-content" data-navlink="item-terms">
    <div class="title mt-3">
        Terms and Conditions
    </div>
    <div class="content mt-3">
        <p>
            At vero eos censes tantas res gessisse sine causa? quae fuerit causa, nollem. Omne animal, simul atque
            natum sit, amet, consectetur, adipisci velit, sed quia voluptas. Sed ut dolore suo sanciret militaris
            imperii disciplinam exercitumque in gravissimo bello animadversionis. Laudem et via procedat oratio
            quaerimus igitur, quid iudicat, quo enim maxime consuevit.
        </p>
        <p>
            At vero eos censes tantas res gessisse sine causa? quae fuerit causa, nollem. Omne animal, simul atque
            natum sit, amet, consectetur, adipisci velit, sed quia voluptas. Sed ut dolore suo sanciret militaris
            imperii disciplinam exercitumque in gravissimo bello animadversionis. Laudem et via procedat oratio
            quaerimus igitur, quid iudicat, quo enim maxime consuevit.At vero eos censes tantas res gessisse sine
            causa? quae fuerit causa, nollem. Omne animal, simul atque natum sit, amet, consectetur, adipisci velit,
            sed quia voluptas. Sed ut dolore suo sanciret militaris imperii disciplinam exercitumque in gravissimo
            bello animadversionis. Laudem et via procedat oratio quaerimus igitur, quid iudicat, quo enim maxime
            consuevit.
        </p>
        <p>
            At vero eos censes tantas res gessisse sine causa? quae fuerit causa, nollem. Omne animal, simul atque
            natum sit, amet, consectetur, adipisci velit, sed quia voluptas. Sed ut dolore suo sanciret militaris
            imperii disciplinam exercitumque in gravissimo bello animadversionis. Laudem et via procedat oratio
            quaerimus igitur, quid iudicat, quo enim maxime consuevit. At vero eos censes tantas res gessisse sine
            causa? quae fuerit causa, nollem. Omne animal, simul atque natum sit, amet, consectetur, adipisci velit,
            sed quia voluptas. Sed ut dolore suo sanciret militaris imperii disciplinam exercitumque in gravissimo
            bello animadversionis. Laudem et via procedat oratio quaerimus igitur, quid iudicat, quo enim maxime
            consuevit.
        </p>
        At vero eos censes tantas res gessisse sine causa? quae fuerit causa, nollem. Omne animal, simul atque
        natum sit, amet, consectetur, adipisci velit, sed quia voluptas. Sed ut dolore suo sanciret militaris
        imperii disciplinam exercitumque in gravissimo bello animadversionis. Laudem et via procedat oratio
        quaerimus igitur, quid iudicat, quo enim maxime consuevit.At At vero eos censes tantas res gessisse sine
        causa? quae fuerit causa, nollem. Omne animal, simul atque natum sit, amet, consectetur, adipisci velit,
        sed quia voluptas. Sed ut dolore suo sanciret militaris imperii disciplinam exercitumque in gravissimo
        bello animadversionis. Laudem et via procedat oratio quaerimus igitur, quid iudicat, quo enim maxime
        consuevit.At vero eos censes tantas res gessisse vero eos censes tantas res gessisse sine causa? quae
        fuerit causa, nollem. Omne animal, simul atque natum sit, amet, consectetur, adipisci velit, sed quia
        voluptas. Sed ut dolore suo sanciret militaris imperii disciplinam exercitumque in gravissimo bello
        animadversionis. Laudem et via procedat oratio quaerimus igitur, quid iudicat, quo enim maxime.
        <p></p>
        At vero eos censes tantas res gessisse sine causa? quae fuerit causa, nollem. Omne animal, simul atque
        natum sit, amet, consectetur, adipisci velit, sed quia voluptas. Sed ut dolore suo sanciret militaris
        imperii disciplinam exercitumque in gravissimo bello animadversionis. Laudem et via procedat oratio
        quaerimus igitur, quid iudicat, quo enim maxime consuevit. At vero eos censes tantas res gessisse sine
        causa? quae fuerit causa, nollem. Omne animal, simul atque natum sit, amet, consectetur, adipisci velit,
        sed quia voluptas. Sed ut dolore suo sanciret militaris imperii disciplinam exercitumque in gravissimo
        bello animadversionis. Laudem et via procedat oratio quaerimus igitur, quid iudicat, quo enim maxime
        consuevit.
        </p>
    </div>
    <div class="bottom mt-5">
        <div class="disagree btn-cus btn-cus-primary mr-3" onclick="onDisagreeTerms()">Disagree</div>
        <div class="agree btn-cus btn-cus-secondary" onclick="onAgreeTerms()">Agree</div>
    </div>
</div>