dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('home-page', home_page, name='home_page'),
    path('home-page-public', home_page_public, name='home_page_public'),
]

new_campaign_urlpatterns = [
    path('crowdfunding/public/<str:campaign_id>/preview', cf_public_preview, name='cf_public_preview'),
    path('new-campaign/<str:campaign_id>/<str:create_or_update>', new_campaign, name='new_campaign'),
    path('create-new-campaign', create_new_campaign, name='create_new_campaign'),
    path('publish-new-campaign/<str:campaign_id>', publish_new_campaign, name='publish_new_campaign'),
    path('pick-plan', pick_plan, name='pick_plan'),

    # ajax
    path('new-campaign-process/<str:process>', new_campaign_process, name='new_campaign_process'),
    path('new-campaign-process-delete', new_campaign_process_delete, name='new_campaign_process_delete'),
    path('small-medias-upload', small_medias_upload, name='small_medias_upload'),
]

urlpatterns += new_campaign_urlpatterns

cf_urlpatterns = [
    path('crowdfunding/public/<str:campaign_id>', cf_public, name='cf_public'),
    path('crowdfunding/manager', cf_manager, name='cf_manager'),
]

urlpatterns += cf_urlpatterns

giving_pilot/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def test(request):
    return render(request, 'icons/temp.html')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
] + [path('test', test, name='test')]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.urls import path

app_name = 'landing'

urlpatterns = [

]

dashboard/views/crowdfunding.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404

from dashboard.models import Media
from dashboard.permissions import is_campaign_owner
from dashboard.utils import *


def cf_public(request, campaign_id):
    campaign = get_object_or_404(Campaign, id=campaign_id)
    small_medias = Media.objects.filter(campaign=campaign).order_by('-created_at')
    context = {
        'campaign': campaign,
        'small_medias': small_medias,
        'campaigns': Utils.get_all_published_campaigns(),
        'is_public': True,
    }

    return render(request, 'dashboard/crowdfunding/public/cf_public.html', context)


@is_campaign_owner
def cf_manager(request):
    return render(request, 'dashboard/crowdfunding/manager/cf_manager.html')


@login_required
@is_campaign_owner
def cf_public_preview(request, campaign_id):
    campaign = get_object_or_404(Campaign, id=campaign_id)
    small_medias = Media.objects.filter(campaign=campaign).order_by('-created_at')
    context = {
        'campaign': campaign,
        'campaigns': Utils.get_all_published_campaigns(),
        'small_medias': small_medias,
        'is_preview': True,
    }
    return render(request, 'dashboard/crowdfunding/public/cf_public_preview.html', context)

dashboard/views/new_campaign.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt

from accounts.models import User
from dashboard.models import Media, Category
from dashboard.permissions import is_campaign_owner
from dashboard.utils import *


@login_required
def create_new_campaign(request):
    user = User.objects.get(username=request.user.username)
    campaign = Campaign(owner=user)
    campaign.save()
    return redirect(f'/dashboard/new-campaign/{campaign.id}/create')


@login_required
@is_campaign_owner
def publish_new_campaign(request, campaign_id):
    campaign = get_object_or_404(Campaign, id=campaign_id)
    campaign.is_published = True
    campaign.save()
    return redirect('dashboard:home_page')


@login_required
def new_campaign(request, campaign_id, create_or_update):
    campaign = get_object_or_404(Campaign, id=campaign_id)
    small_medias = Media.objects.filter(campaign=campaign).order_by('-created_at')
    context = {
        'campaign_id': campaign_id,
        'campaign': campaign,
        'is_update_url': True if create_or_update == 'update' else False,
        'categories': Category.objects.all(),
        'small_medias': small_medias,
        'tags': campaign.tags.split(', ') if campaign.tags else [],
        'causes': campaign.cause.split(', ') if campaign.cause else [],
        'on_creating': True
    }
    if campaign.organization_name or campaign.title or campaign.category:
        context['is_update'] = True
    if 'tab' in request.GET:
        context['tab'] = request.GET.get('tab').strip()
    if 'tag' in request.GET:
        context['tag'] = request.GET.get('tag').strip()
    return render(request, 'dashboard/new_campaign/campaign_base.html', context)


@login_required
@csrf_exempt
def new_campaign_process(request, process):
    if request.method == 'POST':
        uuid = request.POST.get('uuid')
        campaign = Campaign.objects.get(id=uuid)
        if process == 'basic_info':
            org_name = request.POST.get('org_name')
            org_description = request.POST.get('org_description')
            if request.FILES:
                org_logo = request.FILES.popitem()[1][0]
                campaign.organization_logo = org_logo
            campaign.organization_name = org_name
            campaign.organization_description = org_description
        if process == 'about_campaign':
            camp_title = request.POST.get('camp_title')
            camp_description = request.POST.get('camp_description')
            # camp_cause = request.POST.get('camp_cause')
            camp_start_date = request.POST.get('camp_start_date')
            has_camp_end_date = request.POST.get('has_camp_end_date')
            camp_end_date = request.POST.get('camp_end_date')
            has_goal_amount = request.POST.get('has_goal_amount')
            camp_goal_amount = request.POST.get('camp_goal_amount')
            campaign.title = camp_title
            campaign.description = camp_description
            # campaign.cause = camp_cause
            is_update = True if request.POST['is_update'] == 'true' else False
            thumbnail_path = ''
            print(123123123, is_update)
            if is_update:
                if campaign.large_media:
                    try:
                        os.remove(os.path.join(settings.MEDIA_ROOT, campaign.large_media.name))
                    except:
                        pass
                if campaign.large_image:
                    try:
                        os.remove(os.path.join(settings.MEDIA_ROOT, campaign.large_image.replace('media/', '')))
                    except:
                        pass
                if campaign.large_media_thumbnail:
                    t_url = campaign.large_media_thumbnail.replace(Utils.get_protocol_and_host(request), '').replace(
                        'media/', '')
                    try:
                        os.remove(os.path.join(settings.MEDIA_ROOT, t_url))
                    except:
                        pass
                campaign.large_media = ''
                campaign.large_image = ''
                campaign.large_media_url = ''
                campaign.large_is_video = False
            if request.FILES:
                campaign.large_media = request.FILES.popitem()[1][0]
                campaign.save()
                thumbnail_path = os.path.join(Utils.get_protocol_and_host(request), 'media', 'thumbnail',
                                              Utils.get_thumbnail(campaign.large_media.name, media_type='video'))
                campaign.large_is_video = True

            elif 'canvas' in request.POST:
                campaign.large_image = base64_to_image(bs64_data=request.POST['canvas'],
                                                       username=request.POST['username'])
                thumbnail_path = os.path.join(Utils.get_protocol_and_host(request), 'media', 'thumbnail',
                                              Utils.get_thumbnail(campaign.large_image, media_type='image'))
            elif 'url' in request.POST:
                campaign.large_media_url = request.POST.get('url')
                thumbnail_path = os.path.join(Utils.get_protocol_and_host(request), 'media', 'thumbnail',
                                              Utils.get_thumbnail(campaign.large_media_url, media_type='url'))
                campaign.large_is_video = True
            if thumbnail_path != '':
                campaign.large_media_thumbnail = thumbnail_path + '_thumbnail.jpg'
                campaign.large_media_cover = thumbnail_path + '_cover.jpg'
                campaign.large_media_cover_small = thumbnail_path + '_cover_small.jpg'
            campaign.start_date = camp_start_date
            campaign.has_end_date = True if has_camp_end_date == 'true' else False
            if has_camp_end_date == 'false':
                campaign.end_date = datetime.date.today() + datetime.timedelta(days=720)
            else:
                campaign.end_date = camp_end_date
            campaign.has_goal_amount = True if has_goal_amount == 'true' else False
            campaign.goal_amount = camp_goal_amount
        if process == 'about_you':
            your_name = request.POST.get('your_name')
            your_email = request.POST.get('your_email')
            your_phone = request.POST.get('your_phone')
            your_title = request.POST.get('your_title')
            is_your_email_private = True if request.POST.get('is_your_email_private') == 'true' else False
            is_your_phone_private = True if request.POST.get('is_your_phone_private') == 'true' else False
            is_your_title_private = True if request.POST.get('is_your_title_private') == 'true' else False
            campaign.full_name = your_name
            campaign.second_email = your_email
            campaign.mobile = your_phone
            campaign.your_title = your_title
            campaign.is_your_title_private = is_your_title_private
            campaign.is_mobile_private = is_your_phone_private
            campaign.is_email_private = is_your_email_private
        if process == 'other_options':
            category_id = request.POST.get('category')
            tags = request.POST.get('tags')
            is_camp_searchable = True if request.POST.get('is_camp_searchable') == 'true' else False
            is_camp_private = True if request.POST.get('is_camp_private') == 'true' else False
            category = Category.objects.get(id=category_id)
            campaign.category = category
            campaign.is_campaign_searchable = is_camp_searchable
            campaign.tags = tags
            campaign.is_campaign_private = is_camp_private
        campaign.save()

        return JsonResponse({
            'result': 'success'
        }, status=201)


@csrf_exempt
def new_campaign_process_delete(request):
    if request.method == 'POST':
        uuid = request.POST.get('uuid')
        # Campaign.objects.filter(id=uuid).delete()
        return JsonResponse({
            'result': 'success'
        }, status=202)


@csrf_exempt
def small_medias_upload(request):
    if request.method == 'POST':
        uuid = request.POST.get('uuid')
        campaign = get_object_or_404(Campaign, id=uuid)
        keep_media_ids = [value for key, value in request.POST.items() if 'media_id_' in key]
        is_created_indices = [key.replace('is_created_', '') for key in request.POST if 'is_created_' in key]
        medias = Media.objects.filter(campaign=campaign).exclude(id__in=keep_media_ids)
        for media in medias:
            if media.file:
                os.remove(os.path.join(settings.MEDIA_ROOT, media.file.name))
            if media.image:
                os.remove(os.path.join(settings.MEDIA_ROOT, media.image.replace('media/', '')))
            if media.thumbnail:
                t_url = media.thumbnail.replace(Utils.get_protocol_and_host(request), '').replace('media/', '')
                os.remove(os.path.join(settings.MEDIA_ROOT, t_url))
        medias.delete()
        for index in is_created_indices:
            if 'canvas_' + index in request.POST:
                image = base64_to_image(request.POST['canvas_' + index], request.POST['username'])
                thumbnail_path = os.path.join(Utils.get_protocol_and_host(request), 'media', 'thumbnail',
                                              Utils.get_thumbnail(image, media_type='image', is_small=True))
                Media(campaign=campaign, image=image, thumbnail=thumbnail_path).save()

            elif 'url_' + index in request.POST:
                media_url = request.POST['url_' + index]
                thumbnail_path = os.path.join(Utils.get_protocol_and_host(request), 'media', 'thumbnail',
                                              Utils.get_thumbnail(media_url, media_type='url', is_small=True))

dashboard/templates/dashboard/__search_table.html
{% for campaign in campaigns %}
    <tr>
        <td onclick="onCampaignSearch('{{ campaign.id }}')">
            <div class="logo">
                <img src="{{ campaign.organization_logo.url }}" alt="logo">
            </div>
            <div class="info">
                <div class="campaign-title">{{ campaign.title }}</div>
                <div class="company-name">{{ campaign.organization_name }}</div>
            </div>
            <div style="display: none!important;">{{ campaign.tags }}</div>
        </td>
    </tr>
{% endfor %}

dashboard/templates/dashboard/_sidebar.html
{% load static %}
<div id="sidebar" class="d-flex flex-column border-right">
    <!--
    <div class="hamburger item">
        <div class="lines">
            <div class="line"></div>
            <div class="line mt-auto"></div>
            <div class="line mt-auto"></div>
        </div>
    </div>
    -->
    <div class="house item tab-item" data-tab-link="homepage"><a href="#"><i
            class="item-icon fas fa-home active"></i></a></div>
    <!--
    <div class="meter item tab-item" data-tab-link=""><a href="#"><i class="item-icon fas fa-tachometer-alt"></i></a>
    </div>
    -->
    <div class="plus item tab-item {% if on_creating %}no-action{% endif %}" data-tab-link="create-new-campaign">
        <a href="#"><i
                class="item-icon fas fa-plus"></i></a>
    </div>
    <!--
    <div class="compass item tab-item" data-tab-link=""><a href="#"><i class="item-icon far fa-compass"></i></a></div>
    <div class="bell item tab-item" data-tab-link=""><a href="#"><i class="item-icon far fa-bell"></i></a></div>
    -->
    <div class="profile-photo item {% if is_preview %}with-preview-profile-photo{% endif %}">
        <div class="img">
            <div class="sub-menu">
                <a href="{% url 'logout' %}">Logout</a>
            </div>
        </div>
    </div>
    <div class="hidden-field">
        <input type="text" class="link-info" value="{% if user.is_authenticated %}{% url 'dashboard:home_page' %}
        {% else %}{% url 'dashboard:home_page_public' %}{% endif %}" data-tab-link="homepage" hidden>
        <input type="text" class="link-info" value="{% url 'dashboard:create_new_campaign' %}"
               data-tab-link="create-new-campaign" hidden>
    </div>
</div>

dashboard/templates/dashboard/_topbar.html
{% load static %}
<div id="top-bar" class="border-bottom">
    <div class="hamburger">
        <div class="d-flex d-none flex-column hamburger-icon-open">
            <div class="line"></div>
            <div class="line mt-auto"></div>
            <div class="line mt-auto"></div>
        </div>
        <div class="flex-column d-none hamburger-icon-close">
            <span class="line1"></span>
            <span class="line2"></span>
        </div>
        <div class="drop-menu d-none position-absolute w-100">
            {% if not user.is_authenticated %}
                <a href="{% url 'dashboard:home_page' %}">
                    <div class="text-cus-primary">Get Started</div>
                </a>
                <a href="{% url 'login' %}">
                    <div class="text-cus-primary mt-5">Login</div>
                </a>
                <a href="#">
                    <div class="text-cus-primary mt-5">How it works</div>
                </a>
                <a href="#">
                    <div class="text-cus-primary mt-5">Why US</div>
                </a>
                <a href="#">
                    <div class="text-cus-primary mt-5">Platform</div>
                </a>
                <a href="#">
                    <div class="text-cus-primary mt-5">Contact US</div>
                </a>
            {% else %}
                <a href="{% url 'index' %}">
                    <div class="text-cus-primary">home</div>
                </a>
                <a href="{% url 'dashboard:home_page' %}">
                    <div class="text-cus-primary mt-5">Dashboard</div>
                </a>
                <a href="{% url 'dashboard:create_new_campaign' %}">
                    <div class="text-cus-primary mt-5">+ new campaign</div>
                </a>
                <a href="{% url 'dashboard:home_page' %}">
                    <div class="text-cus-primary mt-5">Explore</div>
                </a>
                <a href="#">
                    <div class="text-cus-primary mt-5">Notification</div>
                </a>
                <a href="#">
                    <div class="text-cus-primary mt-5">My Account</div>
                </a>
                <a href="#">
                    <div class="text-cus-primary mt-5">Logout</div>
                </a>
            {% endif %}

        </div>
    </div>
    <div class="logo">
        <a href="{% if user.is_authenticated %}{% url 'dashboard:home_page' %}{% else %}/{% endif %}">{% include '_logo.html' %}</a>
    </div>
    <div class="search-pc">
        <input type="text" id="pc-search-bar" class="top-search-bar search-bar" placeholder="Search Giving Pilot"
               onkeyup="onSearchGivingPilot('pc-search-bar', false)">
        <div class="search-icon"><i class="fas fa-search"></i></div>
        <div class="search-close d-none"><i class="fas fa-times"></i></div>
        <div class="gp-search-table-wrapper d-none">
            <table id="gp-search-result" class="gp-search-result w-100">
                {% include 'dashboard/__search_table.html' %}
            </table>
            <div class="nothing-found d-none">
                Nothing Found
            </div>
        </div>
    </div>
    <div class="search-mobile">
        <input type="text" id="mobile-search-bar" class="top-search-bar search-bar" placeholder="Search Giving Pilot"
               onkeyup="onSearchGivingPilot('mobile-search-bar', true)">
        <div id="mobile-search-close-icon" class="search-close-icon d-none">
            <img src="{% static 'dashboard/assets/img/close-png.png' %}" class="img" alt="close">
        </div>
        <div id="mobile-search-icon" class="search-icon"><i class="fas fa-search"></i></div>
        <div class="gp-search-table-wrapper d-none">
            <table id="gp-search-result-mobile" class="gp-search-result w-100">
                {% include 'dashboard/__search_table.html' %}
            </table>
            <div class="nothing-found d-none">
                Nothing Found
            </div>
        </div>
    </div>
</div>
<script>
    function onCampaignSearch(campaignId) {
        window.open('/dashboard/crowdfunding/public/'+ campaignId, name='_self');
    }

    function onSearchGivingPilot(inputId, onMobile) {
        // Declare variables
        let input, filter, table, nothing, tr, td, i, txtValue;
        input = document.getElementById(inputId);
        filter = input.value.toUpperCase();
        if (onMobile) {
            table = document.getElementById("gp-search-result-mobile");
        } else {
            table = document.getElementById("gp-search-result");
        }
        tr = table.getElementsByTagName("tr");
        nothing = $('.nothing-found');
        nothing.addClass('d-none');
        // Loop through all table rows, and hide those who don't match the search query
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
        if (table.offsetHeight === 0) {
            nothing.removeClass('d-none');
        }
    }

    $(document).ready(function () {
        const searchBar = $('.top-search-bar');
        const tableWrapper = $('.gp-search-table-wrapper');
        const mobileSearchIcon = $('#mobile-search-icon');
        const mobileSearchCloseIcon = $('#mobile-search-close-icon');
        const mobileSearchBar = $('#mobile-search-bar');
        const $searchBarClose = $('.search-close');
        searchBar.on('focusin onkeyup', function () {
            tableWrapper.removeClass('d-none');
            $searchBarClose.removeClass('d-none');
        });

        $searchBarClose.click(function () {
            $(this).addClass('d-none');
            tableWrapper.addClass('d-none');
            searchBar.val('');
        })

        mobileSearchIcon.click(function () {
            $(this).addClass('d-none');
            mobileSearchCloseIcon.removeClass('d-none');
            tableWrapper.addClass('on-mobile-gp-search-table-wrapper');
            mobileSearchBar.animate({
                width: '100%',
                paddingLeft: '10'
            });
            mobileSearchBar.focus();
        });
        mobileSearchCloseIcon.click(function () {
            $(this).addClass('d-none');
            tableWrapper.addClass('d-none');
            mobileSearchIcon.removeClass('d-none');
            mobileSearchBar.animate({
                width: '0',
                paddingLeft: '0'
            });
        });

        $('.hamburger-icon-open').on('touchstart', function () {
            $(this).removeClass('d-flex');
            $('.hamburger-icon-close').addClass('d-flex');
            $('.drop-menu').toggleClass('d-none');
        });

        $('.hamburger-icon-close').on('touchstart', function () {
            $(this).removeClass('d-flex');
            $('.hamburger-icon-open').addClass('d-flex');
            $('.drop-menu').toggleClass('d-none');
        });
    })


</script>

dashboard/templates/dashboard/dashboard_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}
        Giving Pilot
    {% endblock %}</title>
    <!-- Lato Font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700;900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'accounts/assets/css/vendor/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard/assets/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/assets/css/custom.css' %}">

    <!-- magic scroll  css !-->
    <link rel="stylesheet" href="{% static 'accounts/assets/css/vendor/magicscroll.css' %}">

    <!-- aos css !-->
    {#    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">#}

    <!-- reference your installed Font Awesome Free package's files here -->
    <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>
    <!-- reference your installed Font Awesome Free package's files here -->
    <link href="{% static 'fontawesome_free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <script src="{% static 'accounts/assets/js/vendor/jquery-3.5.1.min.js' %}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/css/splide.min.css">
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/js/splide.min.js"></script>
    {% block extra_style %}
    {% endblock %}
</head>
<body>
{% block cover %}
{% endblock %}
<div id="dashboard-frame" class="d-flex flex-row {% if is_preview %}with-preview-bar{% endif %}">
    {% include 'dashboard/_sidebar.html' %}
    <div id="main" class="d-flex flex-column w-100">
        {% include 'dashboard/_topbar.html' %}
        <div style="padding-top: 82px">
            {% block content %}
            {% endblock %}
        </div>
        {% block footer %}
            {% include '_footer.html' %}
        {% endblock %}
    </div>
    {% block right-bar %}
    {% endblock %}
</div>

<script src="{% static 'dashboard/assets/js/common.js' %}"></script>

<!-- magic scroll js !-->
<script type="text/javascript" src="{% static 'accounts/assets/js/vendor/magicscroll.js' %}"></script>

<!--  datatable js !-->
<script src="{% static 'accounts/assets/js/vendor/jquery.dataTables.min.js' %}"></script>

<!-- boostrap library ~-->
<script src="{% static 'accounts/assets/js/vendor/popper.min.js' %}"></script>
<script src="{% static 'accounts/assets/js/vendor/bootstrap.min.js' %}"></script>

<!-- aos js !-->
{#<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>#}
{#<script>#}
{#    AOS.init();#}
{#</script>#}

<!-- slim scroll js !-->
<script src="{% static 'accounts/assets/js/vendor/jquery.slimscroll.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/js/splide.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@splidejs/splide-extension-video@latest/dist/js/splide-extension-video.min.js"></script>

<script src="{% static 'dashboard/assets/js/slider-preview.js' %}"></script>

{% block extra_script %}
{% endblock %}
</body>
</html>