dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('home-page', home_page, name='home_page'),
    path('home-page-public', home_page_public, name='home_page_public'),
]

new_campaign_urlpatterns = [
    path('crowdfunding/public/<str:campaign_id>/preview', cf_public_preview, name='cf_public_preview'),
    path('new-campaign/<str:campaign_id>/<str:create_or_update>', new_campaign, name='new_campaign'),
    path('create-new-campaign', create_new_campaign, name='create_new_campaign'),
    path('publish-new-campaign/<str:campaign_id>', publish_new_campaign, name='publish_new_campaign'),
    path('pick-plan', pick_plan, name='pick_plan'),

    # ajax
    path('new-campaign-process/<str:process>', new_campaign_process, name='new_campaign_process'),
    path('new-campaign-process-delete', new_campaign_process_delete, name='new_campaign_process_delete'),
    path('small-medias-upload', small_medias_upload, name='small_medias_upload'),
]

urlpatterns += new_campaign_urlpatterns

cf_urlpatterns = [
    path('crowdfunding/public/<str:campaign_id>', cf_public, name='cf_public'),
    path('crowdfunding/manager', cf_manager, name='cf_manager'),
]

urlpatterns += cf_urlpatterns

giving_pilot/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def test(request):
    return render(request, 'icons/temp.html')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
] + [path('test', test, name='test')]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.urls import path

app_name = 'landing'

urlpatterns = [

]

templates/_footer.html
{% load static %}
<div id="footer" class="row w-100 m-0 pb-5">
    <div class="on-pc w-100 row">
        <div class="col-4">
            <div class="d-flex justify-content-center align-items-center">
                <div>
                    {% include '_logo.html' %}
                    <p class="mt-4">Terms and Conditions</p>
                    <p>Privacy Policy</p>
                    <div class="text-cus-secondary">&copy; 2020 GivingPilot</div>
                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="row">
                <div class="col-4">
                    <p class="text-uppercase text-cus-secondary">Giving Pilot</p>
                    <p>Why Us</p>
                    <p>Our Story</p>
                    <p>Contact</p>
                </div>
                <div class="col-4">
                    <p class="text-uppercase text-cus-secondary">How it works</p>
                    <p>Onboarding Process</p>
                    <p>Fundraising Navigator</p>
                    <p>Crowdfunding</p>
{#                    <p>Peer to Peer</p>#}
                </div>
                <div class="col-4">
                    <p class="text-uppercase text-cus-secondary">Journeys</p>
                    <p>Discoveries</p>
                    <p>Plan Your Journey</p>
                    <div class="d-flex justify-content-between" style="max-width: 100px">
                        <a class="" href="#">
                            <div class="facebook"><i class="fab fa-facebook-f"></i></div>
                        </a>
                        <a class="" href="#">
                            <div class="twitter"><i class="fab fa-twitter"></i></div>
                        </a>
                        <a class="" href="#">
                            <div class="linkedin"><i class="fab fa-linkedin-in"></i></div>
                        </a>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="on-mobile w-100">
        <div class="d-flex flex-column text-center">
            <div class="d-flex justify-content-center mb-5">
                {% include '_logo.html' %}
            </div>
            <p class="text-cus-secondary text-uppercase border-top p-4 m-0 ml-5 mr-5">Giving Pilot</p>
            <p class="text-cus-secondary text-uppercase border-top p-4 m-0 ml-5 mr-5">How it works</p>
            <p class="text-cus-secondary text-uppercase border-top p-4 m-0 ml-5 mr-5">Journeys</p>
            <div class="d-flex justify-content-center">
                <div class="d-flex justify-content-between" style="min-width: 100px">
                    <a class="" href="#">
                        <div class="facebook"><i class="fab fa-facebook-f" style="font-size: 26px"></i></div>
                    </a>
                    <a class="" href="#">
                        <div class="twitter"><i class="fab fa-twitter" style="font-size: 26px"></i></div>
                    </a>
                    <a class="" href="#">
                        <div class="linkedin"><i class="fab fa-linkedin-in" style="font-size: 26px"></i></div>
                    </a>
                </div>
            </div>
            <p class="mt-4">Terms and Conditions</p>
            <p>Privacy Policy</p>
            <p class="text-cus-secondary">&copy; 2020 Giving Pilot</p>

        </div>


    </div>
</div>

templates/_logo.html
<?xml version="1.0" encoding="utf-8"?>
<svg width="186px" height="55px" viewbox="0 0 186 55" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <path d="M0 0L185.223 0L185.223 54.7346L0 54.7346L0 0Z" id="path_1" />
    <clipPath id="mask_1">
      <use xlink:href="#path_1" />
    </clipPath>
  </defs>
  <g id="Group-16">
    <path d="M0 0L185.223 0L185.223 54.7346L0 54.7346L0 0Z" id="Clip-2" fill="none" fill-rule="evenodd" stroke="none" />
    <g clip-path="url(#mask_1)">
      <path d="M0.657835 29.4839L5.01063 29.4839L5.01063 10.6406L0.657835 10.6406L0.657835 29.4839ZM0 2.80543C0 2.04453 0.277165 1.38669 0.831929 0.831929C1.38626 0.277598 2.05059 0 2.82449 0C3.61094 0 4.28177 0.277598 4.83654 0.831929C5.39087 1.3737 5.66846 2.03803 5.66846 2.82492C5.66846 3.61181 5.39087 4.28264 4.83654 4.83654C4.29476 5.39173 3.63043 5.66846 2.84398 5.66846C2.05709 5.66846 1.38626 5.39173 0.831929 4.83654C0.277165 4.28264 0 3.60575 0 2.80543L0 2.80543Z" transform="translate(24.069212 14.643858)" id="Fill-1" fill="#223B60" fill-rule="evenodd" stroke="none" />
      <path d="M4.87508 0L9.75016 10.5825L14.6062 0L19.5007 0L9.71161 20.1391L0 0L4.87508 0Z" transform="translate(32.059155 25.284712)" id="Fill-3" fill="#223B60" fill-rule="evenodd" stroke="none" />
      <path d="M0.657835 29.4839L5.01063 29.4839L5.01063 10.6406L0.657835 10.6406L0.657835 29.4839ZM0 2.80543C0 2.04453 0.277598 1.38669 0.831929 0.831929C1.38626 0.277598 2.05059 0 2.82449 0C3.61094 0 4.28177 0.277598 4.83654 0.831929C5.39087 1.3737 5.66846 2.03803 5.66846 2.82492C5.66846 3.61181 5.39087 4.28264 4.83654 4.83654C4.29476 5.39173 3.63043 5.66846 2.84398 5.66846C2.05709 5.66846 1.38626 5.39173 0.831929 4.83654C0.277598 4.28264 0 3.60575 0 2.80543L0 2.80543Z" transform="translate(53.842834 14.643858)" id="Fill-4" fill="#223B60" fill-rule="evenodd" stroke="none" />
      <path d="M0 0.522283L4.37228 0.522283L4.37228 2.26366C5.89366 0.753976 7.60906 0 9.51847 0C11.7107 0 13.4196 0.690315 14.6447 2.06965C15.7023 3.2437 16.2311 5.15874 16.2311 7.81563L16.2311 19.3656L11.8592 19.3656L11.8592 8.84071C11.8592 6.9837 11.6011 5.70051 11.0853 4.99071C10.5825 4.26878 9.66614 3.9076 8.33791 3.9076C6.89362 3.9076 5.86811 4.38528 5.26224 5.33933C4.6685 6.28083 4.37228 7.92563 4.37228 10.2729L4.37228 19.3656L0 19.3656L0 0.522283Z" transform="translate(64.367195 24.762428)" id="Fill-5" fill="#223B60" fill-rule="evenodd" stroke="none" />
      <path d="M0 18.8433L4.3528 18.8433L4.3528 0L0 0L0 18.8433Z" transform="translate(133.56815 25.284409)" id="Fill-6" fill="#223B60" fill-rule="evenodd" stroke="none" />
      <path d="M4.44937 9.88571C4.44937 11.7691 4.9526 13.2585 5.95819 14.3546C6.9902 15.4641 8.35091 16.0184 10.0403 16.0184C11.7427 16.0184 13.1034 15.4706 14.1224 14.3736C15.141 13.278 15.6507 11.8137 15.6507 9.98272C15.6507 8.15083 15.141 6.68705 14.1224 5.59094C13.0904 4.48142 11.7297 3.92709 10.0403 3.92709C8.37646 3.92709 7.02874 4.48142 5.99717 5.59094C4.96516 6.70047 4.44937 8.13134 4.44937 9.88571M0 9.80819C0 7.0872 0.973543 4.77157 2.92106 2.86303C4.86815 0.954488 7.24181 0 10.0403 0C12.8518 0 15.238 0.960984 17.1985 2.88252C19.1331 4.80449 20.1006 7.16429 20.1006 9.96323C20.1006 12.7877 19.1266 15.1544 17.1791 17.0626C15.2185 18.959 12.8133 19.907 9.9628 19.907C7.13831 19.907 4.77157 18.9395 2.86303 17.005C0.954055 15.0964 0 12.6972 0 9.80819" transform="translate(152.41167 24.762472)" id="Fill-7" fill="#223B60" fill-rule="evenodd" stroke="none" />
      <path d="M6.21024 10.9693L6.21024 25.75L1.85744 25.75L1.85744 10.9693L0 10.9693L0 6.90661L1.85744 6.90661L1.85744 0L6.21024 0L6.21024 6.90661L9.59598 6.90661L9.59598 10.9693L6.21024 10.9693Z" transform="translate(175.62656 18.378012)" id="Fill-8" fill="#223B60" fill-rule="evenodd" stroke="none" />
      <path d="M13.6002 14.6109C12.6331 15.824 11.3174 16.4298 9.65358 16.4298C7.98972 16.4298 6.68705 15.8296 5.74555 14.6304C4.88157 13.5348 4.44937 12.1286 4.44937 10.4132C4.44937 8.67181 4.88157 7.2535 5.74555 6.15697C6.70004 4.93181 8.00272 4.31902 9.65358 4.31902C11.2014 4.31902 12.4716 4.87984 13.465 6.00236C14.4451 7.09846 14.9353 8.56224 14.9353 10.3941C14.9353 12.1095 14.4901 13.5153 13.6002 14.6109L13.6002 14.6109ZM19.1621 11.0251C19.1621 10.3565 19.1461 9.74799 19.114 9.19583L19.114 8.03476C19.1127 8.0326 19.1106 8.02827 19.1093 8.02567C18.842 5.50433 17.8494 3.52909 16.1315 2.10213C15.1622 1.29445 14.0384 0.723228 12.7613 0.384567C11.8389 0.129921 10.8346 0 9.74583 0C7.16343 0 5.03791 0.695079 3.36886 2.08567C2.07138 3.16315 1.18791 4.55374 0.718031 6.25614C0.239488 7.5324 0 8.93728 0 10.4708C0 13.2957 0.825 15.6494 2.4763 17.5324C4.11417 19.3899 6.2163 20.3184 8.78311 20.3184C11.0398 20.3184 13.0324 19.4354 14.7612 17.668L14.7612 20.2993C14.7612 24.2069 13.168 26.1609 9.98228 26.1609C8.25433 26.1609 6.93866 25.5737 6.03571 24.4001C5.64898 23.8973 5.37181 23.1814 5.20378 22.2529L0.831929 22.2529C1.08961 24.7162 2.05709 26.6447 3.73394 28.0374C5.35882 29.3917 7.4289 30.0685 9.94374 30.0685C12.9233 30.0685 15.264 29.0885 16.9664 27.128C17.8689 26.1094 18.4757 24.8903 18.7853 23.472C18.888 22.9562 18.9685 22.3594 19.027 21.6821C19.085 21.0052 19.114 20.2218 19.114 19.3314L19.114 11.1013L19.1621 11.0251Z" transform="translate(85.20293 24.351011)" id="Fill-9" fill="#223B60" fill-rule="evenodd" stroke="none" />
      <path d="M14.7183 10.0598C14.7183 11.7626 14.2156 13.1814 13.2095 14.316C12.2291 15.4511 10.9848 16.0189 9.47602 16.0189C8.99402 16.0189 8.54059 15.9669 8.11488 15.8647C7.30201 15.5975 6.59004 15.1116 5.98071 14.4057C4.97339 13.2697 4.46972 11.8493 4.46972 10.1447C4.46972 8.33705 4.96083 6.86504 5.94173 5.72866C6.52811 5.05134 7.205 4.57496 7.97067 4.29693C8.23831 4.22417 8.5198 4.17091 8.81429 4.13713C9.05291 4.11807 9.29587 4.10811 9.54358 4.10811C10.5795 4.10811 11.4699 4.31469 12.2169 4.72567C12.5872 4.97512 12.9311 5.2826 13.2481 5.64854C13.7184 6.19378 14.0731 6.81827 14.3178 7.51768C14.3671 7.70823 14.4122 7.90787 14.4503 8.12051L14.4975 8.12051C14.6434 8.71728 14.7183 9.36343 14.7183 10.0598M19.0031 7.93689C18.7152 5.46622 17.7152 3.52606 15.9994 2.11902C15.6642 1.84272 15.3095 1.59543 14.9375 1.37413C13.5815 0.458622 12.006 0 10.2109 0C9.95976 0 9.71205 0.0116929 9.46736 0.0346457C9.00051 0.036811 8.54969 0.0636614 8.11358 0.112165C7.39295 0.175394 6.71173 0.319606 6.06819 0.542205C4.55894 1.02898 3.27965 1.86394 2.23378 3.05228C1.29488 4.09858 0.663898 5.35059 0.342126 6.80701C0.235157 7.33709 0.150709 7.94945 0.0905118 8.64453C0.0844488 8.71555 0.079685 8.79264 0.0744882 8.86626C0.0441732 9.1915 0.0259843 9.52453 0.0199213 9.86405C0.00692913 10.2395 0 10.6358 0 11.0585L0.0151575 11.0823L0.0151575 29.619L4.36839 29.619L4.36839 18.6974C5.86118 19.5934 7.74331 20.0516 10.0901 20.0031C10.6037 19.9927 11.0385 19.9373 11.4287 19.839C13.4776 19.5965 15.2138 18.6861 16.6338 17.102C18.3232 15.219 19.1681 12.8652 19.1681 10.0407C19.1681 9.30756 19.1127 8.60642 19.0031 7.93689" transform="translate(109.79581 24.762169)" id="Fill-10" fill="#223B60" fill-rule="evenodd" stroke="none" />
      <path d="M13.6006 14.6114C12.6331 15.824 11.3179 16.4298 9.65402 16.4298C7.99016 16.4298 6.68748 15.8296 5.74598 14.6304C4.88201 13.5348 4.4498 12.1286 4.4498 10.4132C4.4498 8.67181 4.88201 7.2535 5.74598 6.1574C6.70047 4.93181 8.00272 4.31902 9.65402 4.31902C11.2014 4.31902 12.472 4.87984 13.465 6.00236C14.4451 7.09846 14.9353 8.56224 14.9353 10.3941C14.9353 12.1095 14.4906 13.5153 13.6006 14.6114L13.6006 14.6114ZM19.1625 11.0251C19.1625 10.3565 19.1461 9.74799 19.114 9.19583L19.114 8.03476C19.1127 8.0326 19.111 8.0287 19.1097 8.02567C18.842 5.50433 17.8499 3.52909 16.1315 2.10213C15.1622 1.29445 14.038 0.723228 12.7609 0.384134C11.8384 0.129921 10.8346 0 9.74626 0C7.16342 0 5.03791 0.695079 3.36929 2.08567C2.07181 3.16358 1.18835 4.55374 0.718031 6.25614C0.239921 7.5324 0 8.93728 0 10.4708C0 13.2957 0.825433 15.6494 2.4763 17.5324C4.11417 19.3899 6.21673 20.3184 8.78311 20.3184C11.0403 20.3184 13.0328 19.4354 14.7612 17.668L14.7612 20.2993C14.7612 24.2069 13.168 26.1609 9.98272 26.1609C8.25433 26.1609 6.93866 25.5737 6.03614 24.4005C5.64941 23.8973 5.37181 23.1814 5.20421 22.2533L0.831929 22.2533C1.09004 24.7162 2.05709 26.6447 3.73394 28.0374C5.35925 29.3917 7.42933 30.0685 9.94417 30.0685C12.9237 30.0685 15.2644 29.0885 16.9669 27.128C17.8694 26.1094 18.4757 24.8903 18.7853 23.472C18.8884 22.9562 18.9689 22.3594 19.027 21.6821C19.0854 21.0052 19.114 20.2218 19.114 19.3314L19.114 11.1018L19.1625 11.0251Z" transform="translate(-0.00017322834 24.66607)" id="Fill-11" fill="#223B60" fill-rule="evenodd" stroke="none" />
      <path d="M1.50622 2.02591L0 0.866142L0 23.3131L4.3528 23.3131L4.3528 0L1.50622 2.02591Z" transform="translate(143.43498 20.814728)" id="Fill-12" fill="#223B60" fill-rule="evenodd" stroke="none" />
      <path d="M0 12.854L9.63843 20.2738L38.1241 0L0 12.854Z" transform="translate(135.32738 -0.00017322834)" id="Fill-13" fill="#48C6F0" fill-rule="evenodd" stroke="none" />
      <path d="M7.54106 11.6093L47.4763 0L0 5.90232L7.54106 11.6093Z" transform="translate(125.97516 -0.00021653544)" id="Fill-14" fill="#48C6F0" fill-rule="evenodd" stroke="none" />
      <path d="M0.085748 6.75764L5.38957 4.10595L0 0L0.085748 6.75764Z" transform="translate(133.61635 13.538272)" id="Fill-15" fill="#48C6F0" fill-rule="evenodd" stroke="none" />
    </g>
  </g>
</svg>

templates/_navbar.html
{% load static %}

<div id="navbar" class="d-flex flex-column">
    <div class="row top-bar w-100 m-0">
        <div class="col-md-3 col-lg-4 col-xl-5 d-none d-md-flex"></div>
        <div class="col-md-9 col-lg-8 col-xl-7 right-bar row m-0">
            <div class="text-group col-8 d-none d-md-flex">
                <div class="d-flex justify-content-between w-100">
                    <a href="#">
                        <div class="nav-text">
                            Contact Us
                        </div>
                    </a>
                    {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}">
                            <div class="nav-text">
                                Logout
                            </div>
                        </a>
                    {% else %}
                        <a href="{% url 'login' %}">
                            <div class="nav-text">
                                Login
                            </div>
                        </a>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <a href="{% url 'dashboard:home_page' %}" class="get-started">
                            <div class="btn-cus-primary">
                                Dashboard
                            </div>
                        </a>
                    {% else %}
                        <a href="{% url 'sign_up' %}" class="get-started">
                            <div class="btn-cus-primary">
                                Get Started
                            </div>
                        </a>
                    {% endif %}
                </div>


            </div>
            <div class="icon-group col-4 h-100 d-flex justify-content-around">
                <a class="" href="#">
                    <div class="facebook"><i class="icon fab fa-facebook-f"></i></div>
                </a>
                <a class="" href="#">
                    <div class="twitter"><i class="icon fab fa-twitter"></i></div>
                </a>
                <a class="" href="#">
                    <div class="linkedin"><i class="icon fab fa-linkedin-in"></i></div>
                </a>
            </div>
        </div>
    </div>
    <div class="bottom-bar row w-100 m-0">
        <div class="col-xl-5 col-md-4 d-flex align-items-center">
            <div class="logo position-absolute">
                <a href="{% if user.is_authenticated %}{% url 'dashboard:home_page' %}{% else %}/{% endif %}">{% include '_logo.html' %}</a>
            </div>
        </div>
        <div class="col-xl-7 col-md-8 d-none d-md-flex">
            <div class="right-bar d-flex justify-content-between w-100">
                <a href="{% url 'dashboard:home_page_public' %}">
                    <div class="nav-text">Explore Campaigns</div>
                </a>
                <a href="#">
                    <div class="nav-text">how it works</div>
                </a>
                <a href="#">
                    <div class="nav-text">why us</div>
                </a>
                <a href="#">
                    <div class="nav-text">platform</div>
                </a>
            </div>
        </div>
        <div class="d-block d-md-none hamburger">
            <div class="d-flex justify-content-center align-items-center h-100">
                <div class="d-flex d-none flex-column hamburger-icon-open">
                    <span class="line"></span>
                    <span class="line mt-auto"></span>
                    <span class="line mt-auto"></span>
                </div>
                <div class="flex-column d-none hamburger-icon-close">
                    <span class="line1"></span>
                    <span class="line2"></span>
                </div>
            </div>
            <div class="drop-menu position-absolute d-none">
                {% if user.is_authenticated %}
                    <a href="{% url 'dashboard:home_page' %}">
                        <div class="text-cus-primary">Dashboard</div>
                    </a>
                {% else %}
                    <a href="{% url 'sign_up' %}">
                        <div class="text-cus-primary">Get Started</div>
                    </a>
                {% endif %}

                {% if not user.is_authenticated %}
                    <a href="{% url 'login' %}">
                        <div class="text-cus-primary mt-5">Login</div>
                    </a>
                {% else %}
                    <a href="{% url 'logout' %}">
                        <div class="text-cus-primary mt-5">LogOUT</div>
                    </a>
                {% endif %}
                <a href="{% url 'dashboard:home_page_public' %}">
                    <div class="text-cus-primary mt-5">Explore Campaigns</div>
                </a>
                <a href="#">
                    <div class="text-cus-primary mt-5">How it works</div>
                </a>
                <a href="#">
                    <div class="text-cus-primary mt-5">Why US</div>
                </a>
                <a href="#">
                    <div class="text-cus-primary mt-5">Platform</div>
                </a>
                <a href="#">
                    <div class="text-cus-primary mt-5">Contact US</div>
                </a>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.hamburger-icon-open').on('touchstart', function () {
            $(this).removeClass('d-flex');
            $('.hamburger-icon-close').addClass('d-flex');
            $('.drop-menu').toggleClass('d-none');
        });
        $('.hamburger-icon-close').on('touchstart', function () {
            $(this).removeClass('d-flex');
            $('.hamburger-icon-open').addClass('d-flex');
            $('.drop-menu').toggleClass('d-none');
        });
    })
</script>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}
        Giving Pilot
    {% endblock %}</title>
    <!-- Lato Font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700;900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'accounts/assets/css/vendor/bootstrap.css' %}">

    <link rel="stylesheet" href="{% static 'accounts/assets/css/custom.css' %}">
    <!-- AOS css
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    !-->
    <!-- reference your installed Font Awesome Free package's files here -->
    <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>
    <!-- reference your installed Font Awesome Free package's files here -->
    <link href="{% static 'fontawesome_free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Animation View css !-->
    <link rel="stylesheet" href="{% static 'accounts/assets/css/vendor/animate.min.css' %}"/>

    <script src="{% static 'accounts/assets/js/vendor/jquery-3.5.1.min.js' %}"></script>

    <!-- Animation View js !-->
    <script src="{% static 'accounts/assets/js/vendor/jquery.aniview.js' %}"></script>

    <!-- Splide css & js !-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/css/splide.min.css">
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/js/splide.min.js"></script>

    {% block extra_style %}
    {% endblock %}
</head>
<body>
{% include '_navbar.html' %}
{% block content %}

{% endblock %}
{% include '_footer.html' %}

<!--  datatable js !-->
<script src="{% static 'accounts/assets/js/vendor/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'dashboard/assets/js/common.js' %}"></script>

<!-- boostrap library !-->
<script src="{% static 'accounts/assets/js/vendor/popper.min.js' %}"></script>
<script src="{% static 'accounts/assets/js/vendor/bootstrap.min.js' %}"></script>


<script>
    $(document).ready(function () {
        let animationOptions = {
            animateThreshold: 100,
            scrollPollInterval: 20
        };
        $('.aniview').AniView(animationOptions);
    });
</script>
<!--
<script src="{% static 'accounts/assets/js/vendor/aos.js' %}"></script>
<script>
    AOS.init();
</script>
!-->
{% block extra_script %}

{% endblock %}
</body>
</html>